import type { Metadata } from "next";
import "./globals.css";
import { Do_Hyeon } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const do_hyeon = Do_Hyeon({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-Do_Hyeon",
});
const noto_jp = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-Noto_Sans_JP",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-custom antialiased`}>{children}</body>
    </html>
  );
}
